### ISSUE TITLE
Request for adding flag to not render truncate-multiline--button

### ISSUE THREAD

**Issue by swidjaja** [nickiaconis/ember-truncate#37]
We are currently using this add-on to truncate a text on our "button" element. Below is the example of our template
```
<button class="do-something-btn" {{action 'doSomething'}}>
  <span class="some-text">
    {{truncate-multiline text=someText lines=lineCount showButton=false}}
  </span>
</button>
```
The idea here is we just want to truncate the text and do not want to show the see more button. However, we will get HTML validation error because of this nested button.

Will it possible to add another flag - something like `renderShowMoreButton` to the component? When the `renderShowMoreButton` is false, then the button won't be rendered.

Thanks,
Sugi

**Comment by nickiaconis** [comment]
#30 should resolve this. It will be landing soon.

**Comment by swidjaja** [comment]
@nickiaconis We have the latest version - `0.3.2` but we still see the button
<img width="726" alt="screen shot 2018-01-24 at 4 15 15 pm" src="https://user-images.githubusercontent.com/2213508/35364051-f9fe7300-0121-11e8-9e8d-592027caa675.png">

**Comment by nickiaconis** [comment]
Hi @swidjaja, `1.0.0` is the latest version and should allow you to resolve this issue.

**Comment by lougreenwood** [comment]
@nickiaconis What's the flag to disable the button, seems it's not documented?

Cheers

**Comment by lougreenwood** [comment]
@nickiaconis bump on the above :)

**Comment by harshabadami** [comment]
@nickiaconis Bump on this :) Is there a flag to disable the button in 1.0.0? Couldn't find it in the documentation or the code.

**Comment by lougreenwood** [comment]
@nickiaconis I know you probably don't want to be hassled on this... who knows what larger priorities you have :) - but I've taken another look at the commits in #30 again and I can't see how that exposes an API to disable showing the 'show more' button.

Fair enough if your busy, but please let those of us who have been waiting on a followup to your 25th Jan comment know that you're busy so we can find an alternate solution....

**Comment by nickiaconis** [comment]
Hey there @lougreenwood, @harshabadami, sorry for the radio silence.

There isn't a flag for this. Instead, it's controlled by compositional components.

If you check out the [truncate attribute](https://github.com/nickiaconis/ember-truncate#truncate) section of the README, it gives an example that omits the button.

**Comment by lougreenwood** [comment]
Works perfectly! Thanks @nickiaconis!

**Comment by nickiaconis** [comment]
Glad to hear it @lougreenwood! I'll go ahead and close the ticket since it's working.
